### ISSUE TITLE
Under promotion issue?

### ISSUE THREAD

**Issue by BenedictWilkins** [iamlucaswolf/gym-chess#5]
Encoding moves with the alpha zero environment doesnt seem to like pawn under promotions given in UCI format, e.g. f2f1n

I am using the python-chess package to create a move from PGN format (e.g. f1=N) and getting the alpha zero encoding with env.encode(move) which gives f2f1n

Am I doing something wrong?

EDIT: sorry was very tired when I wrote this, please see the comment below giving a more detailed outline of the issue

**Comment by iamlucaswolf** [comment]
Hi @BenedictWilkins ,

thanks for using gym-chess. I'm afraid I didn't fully get that... From my understanding, "f1=n" in PGN equals "f2f1n" in UCI, so the output would actually be correct. Perhaps there was a typo in your question?

**Comment by BenedictWilkins** [comment]
sorry I should have been more clear. I am getting the following error:

Using the following game that contains an under promotion as an example:

e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8b6 g1f3 c8d7 f1e2 c5d4 c3d4 d7b5 b1c3 b5e2 c3e2 f8b4 c1d2 b8c6 e1g1 b4d2 d1d2 g8e7 e2g3 e8g8 a1c1 a8c8 c1c3 c6a5 b2b3 c8c3 d2c3 f8c8 c3d2 a5c6 f1c1 b6b4 g3f1 a7a5 c1c2 b4d2 f1d2 g8f8 g1f1 f8e8 g2g4 e8d7 f1e2 h7h5 h2h3 h5g4 h3g4 f7f6 e5f6 g7f6 d2f1 e6e5 d4e5 f6e5 c2d2 e5e4 f3g5 c8g8 g5e4 d7c7 e4f6 g8g6 f6d5 e7d5 d2d5 g6g4 f1e3 g4g7 d5d2 g7f7 f2f4 c7b6 e2f3 b6c5 d2c2 c5d4 e3g4 f7f8 c2d2 d4c3 d2d7 c3b2 d7b7 b2a2 f3e4 f8e8 g4e5 c6b4 f4f5 a2b3 f5f6 e8f8 f6f7 a5a4 e5c6 a4a3 c6b4 f8f7 b7f7 b3b4 e4d3 a3a2 f7b7 b4a3 d3c2 **a2a1n** c2c3 a3a2 b7b6

Heres an MRE:

```
import chess
import gym
import gym_chess

# GAME (with under promotion)
move_stack = "e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8b6 g1f3 c8d7 f1e2 c5d4 c3d4 d7b5 b1c3 b5e2 c3e2 f8b4 c1d2 b8c6 e1g1 b4d2 d1d2 g8e7 e2g3 e8g8 a1c1 a8c8 c1c3 c6a5 b2b3 c8c3 d2c3 f8c8 c3d2 a5c6 f1c1 b6b4 g3f1 a7a5 c1c2 b4d2 f1d2 g8f8 g1f1 f8e8 g2g4 e8d7 f1e2 h7h5 h2h3 h5g4 h3g4 f7f6 e5f6 g7f6 d2f1 e6e5 d4e5 f6e5 c2d2 e5e4 f3g5 c8g8 g5e4 d7c7 e4f6 g8g6 f6d5 e7d5 d2d5 g6g4 f1e3 g4g7 d5d2 g7f7 f2f4 c7b6 e2f3 b6c5 d2c2 c5d4 e3g4 f7f8 c2d2 d4c3 d2d7 c3b2 d7b7 b2a2 f3e4 f8e8 g4e5 c6b4 f4f5 a2b3 f5f6 e8f8 f6f7 a5a4 e5c6 a4a3 c6b4 f8f7 b7f7 b3b4 e4d3 a3a2 f7b7 b4a3 d3c2 a2a1n c2c3 a3a2 b7b6".split(" ")

board = chess.Board()

# convert string to move stack
for move in move_stack:
    board.push_uci(move)
move_stack = board.move_stack

# create env
env = gym.make('ChessAlphaZero-v0')
env.reset()

for move in move_stack:
    e_move = env.encode(move)
```

gives the following error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-2-d7641f645a3f> in <module>
     18 
     19 for move in move_stack:
---> 20     e_move = env.encode(move)
     21 
     22 

~\Anaconda3\envs\chess\lib\site-packages\gym_chess\alphazero\move_encoding\__init__.py in encode(self, move)
    161 
    162         if action is None:
--> 163             raise ValueError(f"{move} is not a valid move")
    164 
    165         #action = np.ravel_multi_index(

ValueError: a2a1n is not a valid move
```

This seems to happen with any under promotion, let me know if I did something wrong! Thanks in advance.

**Comment by iamlucaswolf** [comment]
Ah, I see. I'm afraid this is nasty, although expected:

**What happened here?**
Both the board and the moves are always encoded w.r.t. the current player. In practical terms, this means that positions in which black is to move are "rotated by 180 degrees", so e.g. a pawn on e7 will be encoded as a d2 pawn. Similarly, moves for the black player are rotated to look like moves from white. Thus, 'a2a1n' becomes 'h7h8n'. (The rationale being that the network must be able to play for both players during MCTS. Not flipping positions/moves to the current player's perspective would force the network to figure out this inherent rotational symmetry and also make the encoding even more complicated.)

The consequence is that an underpromotion must originate at rank 7 and end at rank 8; otherwise it is encoded as a queen move. Queen moves however are also used to promote to a queen, thus the `promotion` property on a `chess.Move` that is encoded as a queen move must be `chess.QUEEN` or `None`.

**In your example, moves were encoded but never made on the board . Thus the current player is always white, and moves for black are never rotated. In fact, every other encoded move will be wrong.**

**How to fix this?**
Simply apply the moves to the environment after encoding them:

```python3
# From your example..

for move in move_stack:
    e_move = env.encode(move)
    env.step(e_move)
```

Let me know if this helps! I know this is far from ideal, perhaps I will give this a makeover when I find the time.

**Comment by BenedictWilkins** [comment]
Yes that seems to resolve the problem! I think this is fine as a solution. Thanks very much for taking the time -- for now it might be worth making a note in documentation to avoid the issue reopening !
